stages:
  - build-assets
  - check-style
  - run-test

build:
  stage: build-assets
  image: node:7.10.1
  variables:
    NODE_ENV: production
  before_script:
    - node --version
    - npm --version
    - npm install --global gulp-cli
    - npm install --only=development
    - npm install --ignore-scripts
  script:
    - gulp
  cache:
    untracked: true
    paths:
      - node_modules
  except:
    - tags

check:
  stage: check-style
  image: python:3.5
  variables:
    ENV: development
    PIP_CACHE_DIR: pip-cache
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
  script:
    - make clean
    - make setup
    - make check
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

test:
  stage: run-test
  image: python:3.5
  variables:
    ENV: test
    PIP_CACHE_DIR: pip-cache
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip setuptools
  script:
    - make setup
    - make clean
    - make coverage
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags
