stages:
  - vet
  - build
  - test

check:
  stage: vet
  image: python:3.5.4
  variables:
    ENV: development
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - pip install flake8 flake8-docstrings -c constraints.txt
    - make clean
  script:
    - make check
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

lint:
  stage: vet
  image: python:3.5.4
  variables:
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - ENV=production make setup
    - ENV=development make setup
    - ENV=test make setup
  script:
    - make lint
  cache:
    untracked: true
    paths:
      - pip-cache
  except:
    - tags

build:
  stage: build
  image: node:8.9.0
  variables:
    NODE_ENV: production
  before_script:
    - node --version
    - npm --version
    - npm install --global gulp-cli
    - npm install --only=development
    - npm install --ignore-scripts
  script:
    - make build
  cache:
    untracked: true
    paths:
      - node_modules
  artifacts:
    untracked: true
    paths:
      - static
  except:
    - tags

test:
  stage: test
  image: python:3.5.4
  variables:
    ENV: test
    PIP_CACHE_DIR: pip-cache
  before_script:
    - pip install --upgrade pip setuptools
    - python --version
    - pip --version
    - make setup
  script:
    - make coverage
  cache:
    untracked: true
    paths:
      - pip-cache
  artifacts:
    untracked: true
    paths:
      - tmp/coverage
  except:
    - tags
